trunk/FacetedOPAC/src/java/mp/hsrky/facetedOpac/model/FacetAuthor.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package mp.hsrky.facetedOpac.model;


import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import mp.hsrky.facetedOpac.service.Connection;

/**
 *
 * @author Administrator
 */
public class FacetAuthor {
private Book[] books;
private java.sql.Connection conn;
private String sCurrentQuery = "";
    public FacetAuthor(String sqlCurrentQuery){
        sCurrentQuery = sqlCurrentQuery;
    }

    public void setBooks(Book[] books)
    {
        this.books = books;
    }

    public FacetType[] getFacetSubject(){
        FacetType[] fts = new FacetType[getCount()];
        String sql = "SELECT DISTINCT(`author`), `id` FROM book_complete where `author` != ''";
        if(sCurrentQuery.compareTo("") > 0)
        {
            sql += " AND `id` IN (" + sCurrentQuery + ")";
        }

        try {
            Connection connection = new Connection();
            conn = connection.getConnection();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            int i = 0;
            while (rs.next()) {
                FacetType ft = new FacetType();
                ft.setValue(rs.getString(1));
                ft.setCount(getTotalAvailable(rs.getString(1)));
                fts[i] = ft;
                i++;
            }
            connection.closeConnection();
        } catch (SQLException sqlEx) {
            sqlEx.printStackTrace();
        }
        return fts;
    }
    public int getCount()
    {
        int ans = 0;
        String sql = "SELECT COUNT(DISTINCT(`author`)) FROM `book_author` WHERE `author` != ''";
        
        try {
            Connection connection = new Connection();
            conn = connection.getConnection();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (rs.next()) {
                ans = rs.getInt(1);
            }
            connection.closeConnection();
        } catch (SQLException sqlEx) {
            sqlEx.printStackTrace();
        }
        return ans;
    }

    private int getTotalAvailable(String sAuthor)
    {
        int total = 0;
        String sql = "SELECT COUNT(DISTINCT(`id`)) FROM book_complete WHERE `author` LIKE '%"+ sAuthor +"%'";
        if(sCurrentQuery.compareTo("") > 0)
        {
           sql += " and `id` IN (" + sCurrentQuery + ")";
        }
        try {
            Connection connection = new Connection();
            conn = connection.getConnection();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (rs.next()) {
                total = rs.getInt(1);
            }
            connection.closeConnection();
        } catch (SQLException sqlEx) {
            sqlEx.printStackTrace();
        }
        return total;
    }
}

trunk/FacetedOPAC/src/java/mp/hsrky/facetedOpac/controller/admin/AddBookController.java
package mp.hsrky.facetedOpac.controller.admin;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import javax.servlet.http.HttpSession;
import mp.hsrky.facetedOpac.model.Book;
import mp.hsrky.facetedOpac.model.DropDown;
import mp.hsrky.facetedOpac.service.AddBook;
import mp.hsrky.facetedOpac.service.AddBookDropDown;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;

public class AddBookController implements Controller {

    private Book book = new Book();
    private ModelAndView modelAndView;
    private HttpSession session;
    public ModelAndView handleRequest(HttpServletRequest request,
            HttpServletResponse response) throws ServletException, IOException {

        session = request.getSession();
        System.out.print("add book session: " + session.getAttribute("username"));

        if(session.getAttribute("username") == null)
        {//session not started
            response.sendRedirect("login.html");
        }
        if (request.getParameter("title") != null) {
            AddBook addBook = new AddBook();
            try {
                book.setAuthor(request.getParameterValues("author"));
                //case description
                book.setDescription(request.getParameter("desc"));
                //case call number
                book.setCall_number(request.getParameter("call_number"));
                //case format
                try
                {
                    int iFormat = Integer.parseInt(request.getParameter("format"), 10);
                    if(addBook.verifyRef("format", iFormat))
                    {
                        book.setIFormat(iFormat);
                    }
                    else
                    {
                        book.setIFormat(addBook.addRef("format", Integer.toString(iFormat)));
                    }
                }catch(Exception e)
                {
                    book.setIFormat(addBook.addRef("format", request.getParameter("format")));
                }
                //book.setImage(request.getParamter("image"));

                //case imprint
                book.setImprint(request.getParameter("imprint"));
                //case isbn
                book.setIsbn(request.getParameterValues("ISBN"));
                //case language
                try
                {
                    int iLanguage = Integer.parseInt(request.getParameter("language"), 10);
                    if(addBook.verifyRef("language", iLanguage))
                    {
                        book.setILanguage(iLanguage);
                    }
                    else
                    {
                        int iNewLanguage = addBook.addRef("language", Integer.toString(iLanguage));
                        book.setILanguage(iNewLanguage);
                    }
                } catch (Exception e) {
                    book.setILanguage(addBook.addRef("language", request.getParameter("language")));
                }
                //case location
                try
                {
                    int iLocation = Integer.parseInt(request.getParameter("location"), 10);
                    if(addBook.verifyRef("location", iLocation))
                    {
                        book.setILocation(iLocation);
                    }
                    else
                    {//if user enter integer as location
                        int iNewLocation = addBook.addRef("location", Integer.toString(iLocation));
                        book.setILocation(iNewLocation);
                    }
                }catch (Exception e){
                    //if the location is new
                    book.setILocation(addBook.addRef("location", request.getParameter("location")));
                }
                //case location link (case when location is online only)
                if (request.getParameter("location_link") != null) {
                    book.setLocation_link(request.getParameter("location_link"));
                }
                else
                {
                    book.setLocation_link("");
                }
                //case publisher
                book.setPublisher(request.getParameter("publisher"));
                //case subject
                book.setSubject(request.getParameterValues("subject"));
                //case title
                book.setTitle(request.getParameter("title"));
                //case year
                book.setYear(Integer.parseInt(request.getParameter("year"), 10));
                
            } catch (Exception e) {
                System.out.print("create book object error: \n" + e);
            }

            
            /* insert record */
            if(addBook.register(book))
            {//add success
                modelAndView = new ModelAndView("admin/addbookPic");
                modelAndView.addObject("bookId", book.getBookId());
                modelAndView.addObject("callNumber", book.getCall_number());
                modelAndView.addObject("bookTitle", book.getTitle());
            }
            else
            {//fail to insert into db
                modelAndView = new ModelAndView("admin/fail");
                modelAndView.addObject("message", "<br /> - Add new book record failed. <a href='addBook.html'>Please try again.</a>");
            }
        }
        else
        {//no input - create form - drop down
            System.out.print("Add book controller: no input detected");
            AddBookDropDown bookDropDown = new AddBookDropDown();
            DropDown dd_format = new DropDown();
            DropDown dd_language = new DropDown();
            DropDown dd_location = new DropDown();
            dd_format = bookDropDown.getRefList("format");
            dd_language = bookDropDown.getRefList("language");
            dd_location = bookDropDown.getRefList("location");

            modelAndView = new ModelAndView("admin/addbook");
            modelAndView.addObject("dd_format", dd_format.getDropDownOption());
            modelAndView.addObject("dd_language", dd_language.getDropDownOption());
            modelAndView.addObject("dd_location", dd_location.getDropDownOption());
        }
        return modelAndView;
    }
}

trunk/FacetedOPAC/src/java/mp/hsrky/facetedOpac/controller/admin/AddBookPicController.java
package mp.hsrky.facetedOpac.controller.admin;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import javax.servlet.http.HttpSession;
import mp.hsrky.facetedOpac.command.UploadPic;
import mp.hsrky.facetedOpac.service.AddBook;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;

public class AddBookPicController extends HttpServlet implements Controller {

    public ModelAndView handleRequest(HttpServletRequest request,
            HttpServletResponse response) throws ServletException, IOException {

        HttpSession session = request.getSession();


        if (session.getAttribute("username") == null) {//session not started
            response.sendRedirect("login.html");
        }
        if (request.getParameter("bookId") != null) {
            //System.out.print(request.getRealPath(request.getContextPath()));
            String pic_path = request.getRealPath("/book_cover/");
            //System.out.print(request.getRealPath("/book_cover/"));
            String filename = "";
            String sBookId = request.getParameter("bookId").trim();
            String sCallNumber = request.getParameter("callNumber").trim().replace(".", "");
            filename = sCallNumber + "00" + sBookId;

            UploadPic uploadPic = new UploadPic();
            uploadPic.init(pic_path, filename);
            uploadPic.doPost(request, response);

            AddBook ab = new AddBook();
            if (uploadPic.getUploadSuccess()) {//upload picture successfully
                ab.updateImagePath(sBookId, "book_cover/" + uploadPic.getNewFileName());
            } else {
                //default is book_cover/default.jpg
                ab.updateImagePath(sBookId, "book_cover/default.jpg");
            }
            response.sendRedirect("home.html");
            ModelAndView modelAndView = new ModelAndView("admin/home");
            modelAndView.addObject("message", "Add book success!");
            return modelAndView;
        } else {
            ModelAndView modelAndView = new ModelAndView("admin/home");
            modelAndView.addObject("message", "Invalid action detected. Please try again.");
            return modelAndView;
        }


    }
}

trunk/FacetedOPAC/src/java/mp/hsrky/facetedOpac/controller/admin/HomeController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mp.hsrky.facetedOpac.controller.admin;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;

public class HomeController extends HttpServlet implements Controller {

    public ModelAndView handleRequest(HttpServletRequest request,
            HttpServletResponse response) throws ServletException, IOException {

        HttpSession session = request.getSession();


        if (session.getAttribute("username") == null) {//session not started
            response.sendRedirect("login.html");
        }

        ModelAndView modelAndView = new ModelAndView("admin/home");
        modelAndView.addObject("message", "");
        return modelAndView;



    }
}

trunk/FacetedOPAC/src/java/mp/hsrky/facetedOpac/controller/admin/LoginController.java
package mp.hsrky.facetedOpac.controller.admin;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import javax.servlet.http.HttpSession;
import mp.hsrky.facetedOpac.command.LoginCommand;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;

public class LoginController implements Controller {

	public ModelAndView handleRequest(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

        if(request.getParameter("logout")!= null)
        {
            HttpSession oldSession = request.getSession();
            oldSession.removeAttribute("username");
            
            oldSession = null;
            response.sendRedirect("login.html");
        }

		ModelAndView modelAndView;
        if((request.getParameter("username") == null || "".equals(request.getParameter("username")))&&
            (request.getParameter("password") == null || "".equals(request.getParameter("password"))))
        {//not value entered
            modelAndView = new ModelAndView("admin/Login");
            modelAndView.addObject("message", null);
        }
        else if (request.getParameter("username") == null || "".equals(request.getParameter("username")))
        {//no username
            modelAndView = new ModelAndView("admin/Login");
            modelAndView.addObject("message", "*Username cannot be empty");
        }
        else if(request.getParameter("password") == null || "".equals(request.getParameter("password")))
        {//no password
            modelAndView = new ModelAndView("admin/Login");
            modelAndView.addObject("message", "*Password cannot be empty");
        }
        else
        {//validating
            LoginCommand lc = new LoginCommand();
            String username = request.getParameter("username").trim();
            username = username.replace("'", "");
            username = username.replace("\"", "");
            username = username.replace("#", "");
            String password = request.getParameter("password").trim();
            password = password.replace("'", "");
            password = password.replace("\"", "");
            password = password.replace("#", "");
            lc.setUsername(username);
            lc.setPassword(password);
            if(lc.authenticate())
            {//authenticated - start session
                HttpSession session = request.getSession(true);
                session.setAttribute("username", lc.getUsername());
                session.setAttribute("name", lc.getName());

                modelAndView = new ModelAndView("admin/home");
                modelAndView.addObject("message", lc.getName());
                response.sendRedirect("home.html");
            }
            else
            {
                modelAndView = new ModelAndView("admin/Login");
                modelAndView.addObject("message", "*Invalid username or password");
            }

        }

		return modelAndView;
	}
}

trunk/FacetedOPAC/src/java/mp/hsrky/facetedOpac/controller/admin/UpdateBookController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package mp.hsrky.facetedOpac.controller.admin;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import mp.hsrky.facetedOpac.model.SimpleSearch;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;

public class UpdateBookController implements Controller {

	public ModelAndView handleRequest(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

		ModelAndView modelAndView = new ModelAndView("admin/updateBook");
        if(!request.getParameterMap().isEmpty())
        {//has request
            String sTitle = request.getParameter("title");
            if(!("".compareTo(sTitle) > 0))
            {
                SimpleSearch ss = new SimpleSearch(sTitle);
                modelAndView.addObject("books", ss.exec());
                modelAndView.addObject("total", ss.execCount());
            }
        }
        else
        {
            modelAndView.addObject("total", 0);
        }

		return modelAndView;
	}
}

trunk/FacetedOPAC/web/WEB-INF/jsp/admin/Login.jsp
<%
response.setHeader("Pragma","no-cache");
response.setHeader("Cache-Control","no-cache");
response.setDateHeader("Expires",0);
%>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
        <title>Faceted OPAC :: Online Public Access Catalog</title>
        <link href="../style/style.css" rel="stylesheet" type="text/css" />
        <link href="../style/facet.css" rel="stylesheet" type="text/css" />
        <link href="../style/newbook.css" rel="stylesheet" type="text/css" />
        <link href="admin.css" rel="stylesheet" type="text/css" />
    </head>

    <body>
        <form id="form1" name="form1" method="post" action="">
            <%@ include file="/WEB-INF/jsp/fragment/admin_header.jsp" %>
            <div id="search_strip">
                <div class="search_query">
                    
                </div>
                <%@ include file="/WEB-INF/jsp/fragment/searchBar.jsp" %>
            </div>
            <div id="body_area" style="margin-left:auto;margin-right:auto;">
                <div class="loginBox">
                    <form method="POST" action="#">
                    <div style="font-size:medium;font-weight:bold;">Administrator Login Page</div>
                    <br />
                    <div>
                        <span class="login-left">Username: </span>
                        <span class="login-right"><input class="login-field" type="text" name="username"/></span>
                    </div>
                    <div style="height:4px;"></div>
                    <div>
                        <span class="login-left">Password : </span>
                        <span class="login-right"><input class="login-field" type="password" name="password"/></span>
                    </div>
                    <br />
                    
                    <input class="login-button" type="submit" value="Login"/>

                    <c:if test="${not empty message}" >
                        <div class="login-fail">${message}</div>
                    </c:if>
                    </form>
                </div>
            </div>
<%@ include file="/WEB-INF/jsp/fragment/admin_footer.jsp" %>
        </form>

    </body>
</html>

trunk/FacetedOPAC/web/WEB-INF/jsp/admin/addbookPic.jsp
<%
        response.setHeader("Pragma", "no-cache");
        response.setHeader("Cache-Control", "no-cache");
        response.setDateHeader("Expires", 0);
%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
        <title>Faceted OPAC :: Online Public Access Catalog</title>
        <link href="../style/style.css" rel="stylesheet" type="text/css" />
        <link href="../style/facet.css" rel="stylesheet" type="text/css" />
        <link href="../style/newbook.css" rel="stylesheet" type="text/css" />
        <link href="admin.css" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="../script/util.js"></script>
        <script type="text/javascript">
            window.onload = function()
            {
                document.getElementById('upload-pic').onclick = function()
                {//upload-pic, image-field
                    var oImage = document.getElementById('image-field');
                    
                    if(!oImage.value)
                    {
                        alert("Please select an image or click the 'Skip' link to proceed.")
                        return false;
                    }
                }
            }
        </script>
    </head>

    <body>
        <%@ include file="/WEB-INF/jsp/fragment/admin_header.jsp" %>
        <div id="search_strip">
            <div class="search_query">
                
            </div>
            <%@ include file="/WEB-INF/jsp/fragment/searchBar.jsp" %>
        </div>
        <div id="body_area">
        <%@ include file="/WEB-INF/jsp/fragment/adminTask.jsp" %>
            <div class="midarea">
                <div class="head">Add book cover for <br />${bookTitle}</div>
                <div class="admin-action">
                    Choose a picture:
                    <c:if test="${empty message}">*${message}</c:if>
                    <form method="POST" action="addbookPic.html?bookId=${bookId}&callNumber=${callNumber}" enctype="multipart/form-data">
                        <table style="margin-top:16px;">
                            <tr valid="top">
                                <td class="insert-new-book-left">Cover picture:</td>
                                <td class="insert-new-book-right"><input id="image-field" type="file" class="input-reg-book" size="25" name="image" />
                                    <input type="hidden" name="MAX_FILE_SIZE" value="500" />
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2" align="left" style="padding-top:12px;">
                                    <input id="upload-pic" type="submit" value="Upload" style="width:120px;"/>
                                    <a href="home.html">Skip</a>
                                </td>
                            </tr>
                        </table>
                    </form>
                </div>
            </div>
        </div>
        <%@ include file="/WEB-INF/jsp/fragment/admin_footer.jsp" %>


    </body>
</html>

trunk/FacetedOPAC/web/WEB-INF/jsp/admin/home.jsp
<%
response.setHeader("Pragma","no-cache");
response.setHeader("Cache-Control","no-cache");
response.setDateHeader("Expires",0);
%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
        <title>Faceted OPAC :: Online Public Access Catalog</title>
        <link href="../style/style.css" rel="stylesheet" type="text/css" />
        <link href="../style/facet.css" rel="stylesheet" type="text/css" />
        <link href="../style/newbook.css" rel="stylesheet" type="text/css" />
        <link href="admin.css" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="../script/util.js"></script>
    </head>

    <body>
        <%@ include file="/WEB-INF/jsp/fragment/admin_header.jsp" %>
        <div id="search_strip">
            <div class="search_query">
                
            </div>
            <%@ include file="/WEB-INF/jsp/fragment/searchBar.jsp" %>
        </div>
        <div id="body_area">
        <%@ include file="/WEB-INF/jsp/fragment/adminTask.jsp" %>
            <div class="midarea">
                <div class="head">Welcome <%= session.getAttribute( "name" ) %> </div>
                <div class="admin-action">
                    Please select a maintenance task from the menu at left hand side.
                </div>
            </div>
        </div>
    <%@ include file="/WEB-INF/jsp/fragment/admin_footer.jsp" %>


    </body>
</html>

trunk/FacetedOPAC/web/WEB-INF/jsp/admin/updateBook.jsp
<%
        response.setHeader("Pragma", "no-cache");
        response.setHeader("Cache-Control", "no-cache");
        response.setDateHeader("Expires", 0);
%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
        <title>Faceted OPAC :: Online Public Access Catalog</title>
        <link href="../style/style.css" rel="stylesheet" type="text/css" />
        <link href="../style/facet.css" rel="stylesheet" type="text/css" />
        <link href="../style/newbook.css" rel="stylesheet" type="text/css" />
        <link href="admin.css" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="../script/util.js"></script>
        <style>
            .title {
                width:450px;
                text-align:left;
                font-size:14px;
                margin-right:8px;
                color:black;
            }
            .action {
                width:25px;
                text-align:right;
                font-size:14px;
                padding-right:8px;
            }
            .number{
                color:black;
                width:8px;
                text-align:left;
            }
            .bottom-border{
                border-bottom:1px dashed grayText;
            }
        </style>
        <script type="text/javascript">
            window.onload = function(){loadfnc()};
            function cfm(url)
            {
                if(confirm("Are you sure?"))
                {
                    window.location = url;
                }
            }
            function loadfnc()
            {
                if(gup('title')!="")
                {
                      try
                      {
                          $('input-title').value = gup('title');
                      }catch(e)
                      {
                          
                      }
                }
            }
        </script>
    </head>

    <body>
        <%@ include file="/WEB-INF/jsp/fragment/admin_header.jsp" %>
        <div id="search_strip">
            <div class="search_query">
                <%@ include file="/WEB-INF/jsp/fragment/searchQuery.jsp" %>
            </div>
            <%@ include file="/WEB-INF/jsp/fragment/searchBar.jsp" %>
        </div>
        <div id="body_area">
        <%@ include file="/WEB-INF/jsp/fragment/adminTask.jsp" %>
            <div class="midarea">
                <div class="head">
                    Please enter title of the book you wish to update:
                </div>
                <form methon="GET" name="book-title" action="updateBook.html">
                    <label for="title" style="font-size:medium;">Title: </label><input id="input-title" name="title" style="width:350px;"/>
                    <input type="submit" value="Search" />
                </form>
                <div class="admin-action">
                    <c:if test="${books != null}">
                    <table>
                        <tr>
                            <th class="title" colspan="4">Book title</th>
                        </tr>
                        <c:forEach var="n" items="${books}" varStatus="a" >
                        <tr>
                            <td class="number bottom-border">${a.count}.</td>
                            <td class="title bottom-border">${n.title}</td>
                            <td class="action bottom-border">
                                <a href="editBook.html?id=${n.bookId}">Edit</a>
                            </td>
                            <td class="action bottom-border">
                                <a href="javascript:cfm('deleteBook.html?id=${n.bookId}')">Delete</a>
                            </td>
                        </tr>
                        </c:forEach>
                    </table>
                    </c:if>
                </div>
            </div>
        </div>
        <%@ include file="/WEB-INF/jsp/fragment/admin_footer.jsp" %>


    </body>
</html>